add the manifest
zhu733756/fluent-operator-devtools pull request #9
Opened 2022-04-10 15:36 UTC by wenchajun

Signed-off-by: chengdehao <dehaocheng@kubesphere.io>

2022-04-11 01:37 UTC, zhu733756 commented on .idea/.gitignore
> +/workspace.xml
.idea/** is needed ?

2022-04-11 01:44 UTC, zhu733756 approved these changes

2022-04-11 03:52 UTC, benjaminhuo requested changes

2022-04-11 03:52 UTC, benjaminhuo commented on README.md
> +    output.fluentd.fluent.io/mode: "true"
`output.fluentd.fluent.io/mode: "true"` should be changed to `filter.fluentd.fluent.io/mode: "fluentd-only"
` for both the selector and output labels

2022-04-11 03:52 UTC, benjaminhuo commented on manifest/fluentbit-fluend/cluster-namespace-mix/fluentbit-config.yaml
> +apiVersion: fluentbit.fluent.io/v1alpha2
```shell
fluentbit-only-mode
- kubelet-log-to-es
- k8s-app-log-to-kafka
fluentbit-to-fluentd-mode
- to-cluster-wide-fluentd
- to-namespaced-wide-fluentd	
- to-cluster-namespaced-mixed-fluentd
- to-multi-tenant-fluentd
- output-to-different-kafka-topics-with-fluentd	
- use-buffer-in-fluentd-output
fluentd-only-mode
- receive-logs-from-http
```

2022-04-13 08:28 UTC, benjaminhuo requested changes

2022-04-13 08:28 UTC, benjaminhuo commented on manifest/fluentbit-to-fluentd-mode/output-to-different-kafka-topics-with-fluentd/fluentbit-config.yaml
> +kind: ClusterFluentBitConfig
We needn't add the same fluentbit stuff into every subfolder of `fluentbit-to-fluentd-mode` repeatedly.
And the same is for the file fluentbit-forward.yaml

2022-04-13 11:48 UTC, benjaminhuo approved these changes

2022-04-13 11:50 UTC, merged